change in ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,6 +3,9 @@ name: CI
 on:
   push:
     branches: [ master ]
+  pull_request:
+  # Allows you to run this workflow manually from the Actions tab
+    branches: [ master ]
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
@@ -58,7 +61,9 @@ jobs:
           parallel: true
       - name: upload common test results on failure
         if: ${{ failure() }}
-        run: tools/gh-upload-to-s3.sh _build/test/logs test_logs
+        run: |
+          tools/gh-upload-to-s3.sh _build/test/logs test_logs
+          exit 1  # Explicitly fail if uploading test results fails
 
   big_tests:
     name: ${{matrix.preset}} on OTP ${{matrix.otp}}
@@ -92,7 +97,9 @@ jobs:
           test-spec: ${{matrix.test-spec}}
       - name: upload common test results on failure
         if: ${{ failure() }}
-        run: tools/gh-upload-to-s3.sh big_tests/ct_report
+        run: |
+          tools/gh-upload-to-s3.sh big_tests/ct_report
+          exit 1  # Explicitly fail if uploading test results fails
       - name: upload big_tests results to GA4
         if: ${{ !cancelled() && github.ref_name == 'master' }}
         run: tools/gh-report-failing-testcases-to-ga4.sh
@@ -123,7 +130,9 @@ jobs:
           test-spec: ${{matrix.test-spec}}
       - name: upload common test results on failure
         if: ${{ failure() }}
-        run: tools/gh-upload-to-s3.sh big_tests/ct_report
+        run: |
+          tools/gh-upload-to-s3.sh big_tests/ct_report
+          exit 1  # Explicitly fail if uploading test results fails
       - name: upload big_tests results to GA4
         if: ${{ !cancelled() && github.ref_name == 'master' }}
         run: tools/gh-report-failing-testcases-to-ga4.sh
